apiVersion: batch.tutorial.kubebuilder.io/v1
kind: CronJob
metadata:
  labels:
    app.kubernetes.io/name: go-k8s
    app.kubernetes.io/managed-by: kustomize
  name: cronjob-sample
spec:
  # TODO(user): Add fields here
